server:
  port: 8777
spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/test?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: fileNameInsertTest
